# Required columns.
required_columns:
- N 
- P
- K 
- temperature
- humidity
- ph
- rainfall
- label


# Data types for columns.
column_data_types:
  N: numeric
  P: numeric
  K: numeric
  temperature: numeric
  humidity: numeric
  ph: numeric
  rainfall: numeric
  label: categorical
 
# Missing threshold.
missing_threshold: 0.3

# Strictly for numeric columns.
ranges:
  N: [0, 140]
  P: [5, 145]
  K: [5, 205]
  temperature: [8, 44]
  humidity: [14, 100]
  ph: [3, 10]
  rainfall: [20, 299]

# Imputation methods.
numerical_imputation: mean
categorical_imputation: mode
date_imputation: mode